# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries.

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [3]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [5]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [6]:
np.array(my_list)  # 1-D array

array([1, 2, 3])

In [7]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix)  # 2-D array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built in methods
* There are lot of built-in ways to generate array

### arange

Return evenly spaced values within a given interval.

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## Zeros and once
Generate arrays of zeros and ones

In [15]:
 np.zeros(5)  # 1-D array

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((5,5))  # 2-D array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [19]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [20]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
np.linspace(0,10,50) # 1-D array

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye
Creates an Identity matrix

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [24]:
np.eye(5,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

## Random 
Numpy also has lots of ways to create random numbers arrays.

## rand 
create an array of given shape and populate it with random samples from a uniform distribution over (0,1)

In [26]:
np.random.rand(2)

array([0.08558468, 0.66651766])

In [27]:
np.random.rand(5,5)

array([[0.3681321 , 0.49875582, 0.55282731, 0.28800687, 0.42652102],
       [0.20991009, 0.49016266, 0.49087809, 0.75029288, 0.86916109],
       [0.62751513, 0.03086011, 0.97735581, 0.81071691, 0.66718101],
       [0.76739237, 0.92379176, 0.10913429, 0.96355014, 0.15527505],
       [0.32078341, 0.90882991, 0.42128956, 0.70281934, 0.58735112]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [28]:
np.random.randn(2)

array([0.10179189, 0.31825945])

In [29]:
np.random.randn(5,5)

array([[-0.72117675,  1.72339521, -0.39390052,  0.61410462,  0.95710838],
       [-0.43355416, -0.47011028,  1.53084806,  0.11717146, -1.83511663],
       [ 0.19010343, -2.12491099, -0.3012597 , -1.2241245 , -0.33180066],
       [-0.68062851,  0.13321296, -0.27811118,  0.69326138,  2.2034273 ],
       [-0.52814281,  0.63325092, -1.13191799, -1.69761377, -0.08751628]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [31]:
np.random.randint(1,100)

55

In [32]:
np.random.randint(1,2)

1

In [33]:
np.random.randint(1,100,10)

array([21, 60, 62, 64, 85, 78, 20,  5, 32, 89])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [34]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
ranarr

array([48, 49, 17, 35, 14, 43, 44, 24,  5, 20])

## Reshape
Returns an array containing the same data with a new shape.

In [38]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [40]:
ranarr

array([48, 49, 17, 35, 14, 43, 44, 24,  5, 20])

In [41]:
ranarr.max()

49

In [42]:
ranarr.argmax()

1

In [43]:
ranarr.min()

5

In [44]:
ranarr.argmin()  

8

## Shape

Shape is an attribute that arrays have (not a method):

In [45]:
# Vector
arr.shape

(25,)

In [47]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [48]:
arr.reshape(5,5).shape

(5, 5)

In [50]:
arr.reshape(25,1)  # it is also 2-D array

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [51]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [52]:
arr.dtype

dtype('int32')